version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
    - ./backend:/app
    env_file:
      - .env
      - .env.db
    restart: on-failure
    depends_on:
      - db
    command: >
      /wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000

  db:
    image: mysql:8.0
    ports:
    - "3308:3306"
    env_file:
      - .env.db
    restart: on-failure
    volumes:
    - ./mysql:/var/lib/mysql

  web:
    image: nginx:alpine
    ports:
    - "80:80"
    restart: on-failure
    volumes:
    - ./dist:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:alpine
    depends_on:
      - app

  celery:
    build:
      context: .
    env_file:
      - .env
      - .env.db
    volumes:
    - ./backend:/app

    depends_on:
      - app
      - redis
      - db
    command: >
      celery -A MAIN_APP worker -l info -B
